package com.example.attackontitancharacterswiki

object CharsData {

    private val charFullNames = arrayOf("Eren Jaeger", "Mikasa Ackerman", "Armin Arlelt",
        "Conny Springer", "Historia Reiss", "Jean Kirschtein", "Sasha Braus", "Reiner Braun", "Annie Leonhart", "Hange Zoe", "Levi Ackerman",
        "Zeke Jaeger", "Floch Forster", "Falco Grice", "Gabi Braun", "Pieck Finger", "Galliard Porco", "Erwin Smith", "Grisha Jaeger", "Carla Jaeger")

    private val gender = arrayOf("Male", "Female", "Male",
        "Male", "Female", "Male", "Female", "Male", "Female","Ambiguous", "Male",
        "Male", "Male", "Male", "Female", "Female", "Male", "Male", "Male", "Female")

    private val species = arrayOf("Human, Intelligent Titan", "Human", "Human, Intelligent Titan",
        "Human", "Human", "Human", "Human", "Human, Intelligent Titan", "Human, Intelligent Titan", "Human", "Human",
        "Human, Intelligent Titan","Human", "Human", "Human", "Human, Intelligent Titan", "Human, Intelligent Titan", "Human", "Human, Intelligent Titan", "Human")

    private val status = arrayOf("Alive", "Alive", "Alive",
        "Alive", "Alive", "Alive", "Deceased", "Alive", "Unknown", "Alive", "Alive",
        "Unknown", "Alive", "Alive", "Alive", "Alive", "Alive", "Deceased", "Deceased", "Deceased")

    private val shortBiodata = arrayOf("Eren Jaeger (エレン・イェーガー Eren Yēgā) is a former member of the Scout Regiment and the main protagonist of Attack on Titan.  He is the only son of Grisha and Carla Jaeger, the younger paternal half brother of Zeke Jaeger,and the current holder of the Attack Titan, Founding Titan, and the War Hammer Titan.\n" + "\n" + "Eren was born and raised in Shiganshina District, which is located on the southern edge of Wall Maria. He lived there until the year 845, when the Colossal and Armored Titans breached the Wall, allowing a flood of Titans to invade and destroy the city. During the incident, Eren witnessed his mother being murdered and eaten by a smiling Titan. This event aroused in Eren an intense hatred towards the Titans, and he swore to wipe all of them off the face of the earth.\n" + "\n" + "Soon afterward, his father, Grisha Jaeger, found him and gave him the key to his basement, instructing Eren to find it at all costs and retake Wall Maria. He then injected Eren with a Titan injection. Two years later, Eren along with his two friends Mikasa Ackermann and Armin Arlelt joined the 104th Cadet Corps.[28] The three successfully graduated, with Eren ranking as the 5th best cadet, and they joined the Scout Regiment following the struggle for Trost.\n" + "\n" + "After finding the basement and unlocking his father's memories, Eren learned about the truth of what the Titans are, as well as the history of Eldia and Marley. Eren then vowed to free his home from their true enemy: the rest of humanity that lives across the sea. Eren currently possesses the power of three Titans. From his father, Eren inherited the Attack and Founding Titan. After eating Lara Tybur during the Raid on Liberio, he gained the War Hammer Titan as well.",
        "Mikasa Ackerman (ミカサ・アッカーマン Mikasa Akkāman) is one of the two deuteragonists of the series. She is the last descendant of the Shogun clan that stayed on Paradis Island, thereby related to the Azumabito family, and holds significant political power in Hizuru.\n" + "\n" + "After her mother and father were murdered by bandits, Mikasa was rescued by Eren. She lived with him and his parents for approximately one year before the Fall of Wall Maria.\n" + "\n" + "Though she desires only to live a peaceful life with Eren, Mikasa chose to follow him into the military—where she is considered the best soldier among the 104th Cadet Corps. She later joined the Scout Regiment to continue following and protecting Eren.",
        "Armin Arlelt (アルミン・アルレルト Arumin Arureruto) is a soldier in the Scout Regiment. He is also a childhood friend of Eren Jaeger and Mikasa Ackermann, and is one of the two deuteragonists of the series. Although he appears to be the physically weakest of the 104th Cadet Corps, his high intelligence and strategic genius makes him an invaluable asset, though he does not consider himself to be one and is known to have low self-esteem. After the battle of Shiganshina District, he took the power of the Titans from Bertholdt Hoover and became the Colossal Titan.",
        "Conny Springer (コニー・スプリンガー Konī Supuringā) a graduate of 104th Cadet Corps, he was ranked 8th out of the top 10. He is a member of the Scout Regiment.",
        "Historia Reiss (ヒストリア・レイス Hisutoria Reisu) is the current Queen of the Walls. She is a graduate of the 104th Cadet Corps and a former member of the Scout Regiment. She is also the illegitimate child of the nobleman Rod Reiss and the last remaining member of the Reiss royal family.\n" + "\n" + "During her cadet days, she went by the name of Christa Lenz (クリスタ・レンズ Kurisuta Renzu?) to take on a new identity, after being coerced into renouncing her name and claim to the Reiss heritage. She eventually reclaimed her true name, becoming an important asset to the Regiment. After a successful Coup d'etat, Historia ascends to the throne and becomes the new queen of the Walls, replacing the old puppet monarch.",
        "Jean Kirschtein (ジャン・キルシュタイン Jan Kirushutain) is a graduate of the 104th Cadet Corps, among whom he ranked the 6th best. Jean hails from Wall Rose's Trost District, and joined the military with hopes of living a peaceful life within the walls as part of the Military Police Regiment, but would later find himself joining the Scout Regiment.",
        "Sasha Braus (サシャ・ブラウス Sasha Burausu) was a member of the Scout Regiment and one of the few former members of the 104th Cadet Corps, of which she was ranked 9th out of the top 10. A compulsive food hoarder with an overly polite way of speech, Sasha originated from Dauper, a village in the southern territory of Wall Rose.",
        "Reiner Braun (ライナー・ブラウン Rainā Buraun) is the Eldian Vice Chief (副長 Fukuchō) of the Warriors and the main protagonist of Attack on Titan from the Marleyan perspective. He is the illegitimate son of an Eldian mother and a Marleyan father who grew up in Liberio's internment zone. Eventually, he was selected as a child to become one of Marley's Warriors. From a young age, he inherited the power of the Armored Titan.\n" + "\n" + "In the year 845, he infiltrated Paradis Island alongside Bertholdt Hoover, Annie Leonhart, and Marcel Galliard as part of an operation to reclaim the Founding Titan. He joined the Scout Regiment after graduating 2nd in the 104th Cadet Corps.",
        "Annie Leonhart (アニ・レオンハート Ani Reonhāto) is a graduate of the 104th Cadet Corps and former member of the Military Police Regiment. Her exceptional skill with swords and unarmed combat earned her the 4th rank, but she is noted to be a lone wolf that struggles to work with others.\n" + "\n" + "She possesses the ability to transform into a Titan known as the Female Titan. She trained from an early age by her father, and is selected as one of Marley's Warriors. In the year 845, she is sent on a mission to retrieve the Founding Titan, along with her fellow Warriors Reiner Braun, Bertholdt Hoover, and Marcel Galliard. As the Female Titan, she served as a major antagonist prior to being exposed and defeated by the Scout Regiment. After her defeat, she crystallized herself and was left in a comatose state. She is currently being held deep underground under the custody of the Scout Regiment.",
        "Hange Zoë (ハンジ・ゾエ Hanji Zoe, also translated as Hans Zoe) is the 14th and current Commander (団長 Danchō) of the Scout Regiment, formerly a section commander (分隊長 Bun-taichō) in charge of the Fourth Squad, until the death of the 13th Commander - Erwin Smith - who named Hange as his successor shortly before. Hange conducts research on Titans to the point of being obsessed with them. As a result, they are deeply interested in Eren Jaeger and his ability to transform into a Titan.",
        "Levi Ackerman (リヴァイ・アッカーマン Rivai Akkāman), often formally referred to as Captain Levi (リヴァイ兵長 Rivai Heichō), is the squad captain (兵士長 Heishichō, lit. \"leader of the soldiers\") of the Special Operations Squad within the Scout Regiment, and is said to be humanity's strongest soldier.",
        "Zeke Jaeger (ジーク・イェーガー Jīku Yēgā) is the former War Chief (戦士長 Senshi-chō) of Marley's Warriors, assigned to take the Founding Titan from the Eldians of Paradis Island. He is the current holder of the Beast Titan, and is considered the strongest warrior by Reiner Braun, contrasting Levi Ackermann's title of \"humanity's strongest soldier.\" He manipulated and deceived both sides of the war between Eldia and Marley in order to achieve his own agenda of causing the extinction of his own people, which he views as \"salvation.\"\n" + "\n" + "He is the son of Grisha Jaeger and Dina Fritz, older half-brother of Eren Jaeger through his father and a member of the Fritz royal family through his mother.",
        "Floch Forster (フロック・フォルスター Furokku Forusutā) is a former recruit (新兵 Shinpei) of the Scout Regiment. He joined the regiment before the return to Shiganshina District, where he was assigned to Klaus Squad. Other than Hange Zoë and Squad Levi, he was the only survivor of the battle. He is one of the Jaegerists and believes that Eren is the only one who can save the \"New Eldian Empire\" (新生エルディア帝国 Shinsei Erudia Teikoku).",
        "Falco Grice (ファルコ・グライス Faruko Guraisu) is an Eldian associated with the Warriors and Reiner Braun. He is the younger brother of Colt Grice.",
        "Gabi Braun (ガビ・ブラウン Gabi Buraun) is an Eldian serving in the Marleyan Military and the cousin of Reiner Braun. She is a candidate (戦士候補生 Senshi Kōho-sei) that is likely to inherit the Armored Titan's power.",
        "Pieck Finger (ピーク・フィンガー Pīku Fingā) is an Eldian who serves as one of Marley's Warriors and is the current inheritor of the Cart Titan.",
        "Porco Galliard (ポルコ・ガリアード Poruko Gariādo) is an Eldian and the younger brother of Marcel Galliard. He is one of Marley's Warriors with the ability to transform into a Titan and the current inheritor of the Jaw Titan.",
        "Erwin Smith (エルヴィン・スミス Eruvin Sumisu) was the 13th commander (団長 Danchō?) of the Scout Regiment. Discerning, intelligent, and widely respected, Erwin was an able commander. While he cared deeply for his men, he did not hesitate to sacrifice them for the good and prosperity of mankind, and his men have proven more than willing to stake their lives at his order. Erwin developed the Long-Distance Enemy Scouting Formation. Due to uncertainty about his future, he later named Hange Zoë as his successor.",
        "Grisha Jaeger (グリシャ・イェーガー Gurisha Yēgā) was an Eldian doctor who originated from the Liberio internment zone in Marley, and was one of the Eldian Restorationists. He was sent on a mission from Eren Kruger to infiltrate the Walls and take the Founding Titan from the Reiss family, and was given the power of the Attack Titan in order to do so. Grisha was taken inside the Walls by Keith Sadies, and settled in the Shiganshina District. He documented the details about Eldia, Marley, the Titans, and his past in three books that he hid in his basement.\n" + "\n" + "In Marley, he was married to Dina Fritz and had a son named Zeke. After being sent to Paradis Island, he re-married to Carla Jaeger and had a second son, Eren Jaeger.",
        "Carla Jaeger (カルラ・イェーガー Karura Yēgā) was the mother of Eren Jaeger and the second wife of doctor Grisha Jaeger.")

    private val charPhotos = intArrayOf(R.drawable.eren, R.drawable.mikasa, R.drawable.armin,
        R.drawable.conny, R.drawable.historia, R.drawable.jean, R.drawable.sasha, R.drawable.reiner, R.drawable.annie, R.drawable.hange, R.drawable.levi,
        R.drawable.zeke, R.drawable.floch,R.drawable.falco, R.drawable.gabi, R.drawable.pieck, R.drawable.porco, R.drawable.erwin, R.drawable.grisha, R.drawable.carla)

    val listData: ArrayList<Chars>
        get() {
            val list = arrayListOf<Chars>()
            for (position in charFullNames.indices){
                val char = Chars()
                char.full_name = charFullNames[position]
                char.biodata_gender = gender[position]
                char.biodata_species = species[position]
                char.biodata_status = status[position]
                char.biodata_short = shortBiodata[position]
                char.photo = charPhotos[position]
                list.add(char)
            }
            return list
        }
}